<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Shubham" failures="1" tests="9" name="TestClasses.MultipleDataLogin" time="74.557" errors="0" timestamp="2021-11-03T18:39:50 IST" skipped="0">
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsernamePassword3Valid" time="9.241"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsernamePassword4Invalid" time="7.321"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsername4Valid" time="6.615"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsername5Invalid" time="6.664"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsername3Invalid" time="7.048"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsername2Valid" time="6.903"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsername1Invalid" time="11.129">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at TestClasses.MultipleDataLogin.dataUsername1Invalid(MultipleDataLogin.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- dataUsername1Invalid -->
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsernamePassword1Invalid" time="9.439"/>
  <system-out/>
  <testcase classname="TestClasses.MultipleDataLogin" name="dataUsernamePassword2Valid" time="10.197"/>
  <system-out/>
</testsuite> <!-- TestClasses.MultipleDataLogin -->
